### PR TITLE
API

### PR DESCRIPTION
**Pull request by elifoster**
This solves #1, adding an API for deleting, creating, editing, searching for, and getting entries in the database.

### CODE REVIEW

**Comment by elifoster** [comment]
Hm. I'm thinking I may want to modernize this, particularly the queries, before we merge it.

**Comment by applehat** [comment]
Alright. Then I won't merge.

I  did push a hotfix for an error we ran into on Hydra, so you may want to marger master into API =)

**Comment by elifoster** [comment]
I don't see any new commits by you?

Also, rebasing > merging :P

**Comment by elifoster** [comment]
@applehat I have modernized the API, so you or some other knowledgeable person should review this.

**Pull request merged**
